### ISSUE TITLE
Expand acceptable bounds beyond 180 and 90

### ISSUE THREAD

**Issue by tmcw** [mapbox/tilelive.js#113]
The bounds checking in tilelive.js is too far on the cautious side and ends up marking common data sources as invalid, as well as datasources that include outside longitude values in order to represent dateline wrapping. These should be expanded to +/-360 and +/-95

**Comment by springmeyer** [comment]
What common datasources?

**Comment by tmcw** [comment]
Most of Natural Earth, for one - I don't have a ton of testing data, but it's the most common thing that I want to drop into our system and that fails.

**Comment by springmeyer** [comment]
Ah, okay.
