### ISSUE TITLE
Copy hang(s) with tilelive-copy + omnivore + stdout

### ISSUE THREAD

**Issue by yhahn** [mapbox/tilelive.js#121]
In testing @dnomadb ran into a situation where this combination of things hangs:

- tilelive-copy
- omnivore source 
- stdout (serialtiles) destination

------

Example command:

    tilelive-copy omnivore:///path/to/data.geojson

My hunch is that there's multiple things causing tilelive-copy hangs in this scenario.

1. source/sink in omnivore need to be closed for node to exit properly. We're getting around this with an explicit process.exit(0) here and this works https://github.com/mapbox/tilelive.js/commit/5f0aab00a376c03f09f0b7d60e6eaf09ee93d78f
2. `tilelive.copy()` will never call the callback when the `dst` passed in is process.stdout because this is a special node stream that never emits `finish` (per https://nodejs.org/api/process.html#process_process_stdout)

------

### Proposal

- [x] let's prove no 2 by adding a copy test like this outstream test (https://github.com/mapbox/tilelive.js/blob/master/test/copy.test.js#L148-L163) but with process.stdout as the outstream
- [x] can/does this need to be the `finish` event? or could it listen for `stop` which is managed by tilelive itself? https://github.com/mapbox/tilelive.js/blob/master/lib/tilelive.js#L389 -- it seems like if we can this would address the issue

cc @dnomadb @GretaCB @rclark

**Comment by rclark** [comment]
Listening to a read-stream event (`stop`, in this case) is a little dubious because, potentially, the write stream has not yet had a chance to perform all its writing. But then, like you say, `process.stdout` is special, and `.writes()` to stdout might be synchronous / guaranteed, my understanding is just fuzzy here.

**Comment by yhahn** [comment]
Hrm, the `stop` event happens on the put stream no? https://github.com/mapbox/tilelive.js/blob/master/lib/tilelive.js#L374

**Comment by rclark** [comment]
Sorry, my bad -- there is no tilelive writable stream in the process.stdout case though.

Instead [the caller has passed in an output stream](https://github.com/mapbox/tilelive.js/blob/master/lib/tilelive.js#L350) and "put" is simply [that stream](https://github.com/mapbox/tilelive.js/blob/master/lib/tilelive.js#L379). In the `bin/tilelive-copy` case that is `process.stdout`.

- We could consider adjusting `bin/tilelive-copy` such that it doesn't allow stdout, but accepts an output file argument.
- `bin/tilelive-copy` could provide `tilelive.copy` with a custom writable stream that writes to stdout *and* emits a finish event, e.g.

```js
var customWritable = new stream.Writable();
customWritable._write = function(chunk, enc, callback) {
  process.stdout.write(chunk);
  callback();
});
```

**Comment by GretaCB** [comment]
Any issue with replacing `stdout` with a tmp file of some kind? I also like the idea of creating a custom writestream function. I can jump on this.

**Comment by springmeyer** [comment]
Small note: I hope `process.exit(0)` can be only a temporary stopgap as this will cause node to crash if any work is being done in the threadpool when it is called (usually not the case but can happen). You would think that `process.exit` would wait for libuv to finish any work, but this is not what I've observed.

**Comment by GretaCB** [comment]
@springmeyer only temporary. About to create a new branch with a more permanent fix.

**Comment by GretaCB** [comment]
Merged and deployed https://github.com/mapbox/unpacker/pull/478
