### ISSUE TITLE
stream.deserialize buffers everything

### ISSUE THREAD

**Issue by tmcw** [mapbox/tilelive.js#131]
https://github.com/mapbox/tilelive.js/blob/master/lib/stream-deserialize.js#L19

It doesn't look like this stream's _buffer member is reset to a value other than "all of the data"

**Comment by yhahn** [comment]
The deserialize transform stream stores incomplete lines at `_buffer` as chunks come in and then replaces this value wholesale here https://github.com/mapbox/tilelive.js/blob/master/lib/stream-deserialize.js#L27 on processing each chunk.

Is there something I'm missing?

**Comment by tmcw** [comment]
:+1: was misreading it.
